// <auto-generated />
using Dos.Database;
using Dos.Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Dos.Database.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20200629110642_AddGuildConfig")]
    partial class AddGuildConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Dos.Database.Models.GuildConfig", b =>
                {
                    b.Property<int>("GuildConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<BotGameConfig>("Config")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildConfigId");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("GuildConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
